sonar.projectKey=quote-app
sonar.projectName=quote-app
sonar.projectVersion=1.0

# Source code location

sonar.sources=src/main/java

# Compiled classes (important)

sonar.java.binaries=target/classes

# Test reports

sonar.junit.reportPaths=target/surefire-reports

# JaCoCo coverage report (optional but good)

sonar.jacoco.reportPaths=target/jacoco.exec

# Encoding

sonar.sourceEncoding=UTF-8

